### ISSUE TITLE
Set emoji width so it doesn't mess up my prompt

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#109]
https://github.com/mandybess/dotfiles/commit/f59d45a55dcbda2692396f49fee87fdd7cdd796a

**Comment by mandybess** [comment]
@gabebw heads up i forgot the second `%` in that commit for the `no gucci` case. I added it here: f652b926993be9f778f6ef3e0948a3b688ea38f0

**Comment by gabebw** [comment]
@mandybess Do you use Terminal (like me) or something else (like iTerm2)? It's still broken for me 😞 

![emoji](https://user-images.githubusercontent.com/257678/39401562-c5e25314-4afc-11e8-9b80-e022fb9f46b6.gif)

**Comment by mandybess** [comment]
I use iTerm which has a setting to allow Unicode 9 characters to be rendered as two character spaces - which is probably what made this work

**Comment by gabebw** [comment]
I think this won't work for me 😭so I will close it
