### ISSUE TITLE
Auto-source vimrc

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#110]
https://github.com/junegunn/dotfiles/blob/627d4d8178137e03ea4d87527d459aa95235b52c/vimrc#L1704

**Comment by gabebw** [comment]
For some reason it's not working:

```vim
let g:x = 'test'
augroup vimrc
  autocmd BufWritePost vimrc,.vimrc nested if expand('%') !~ 'fugitive' | source % | endif
augroup END
```

Changing the value of `g:x` and saving the file doesn't change `:echo g:x`, so it seems to not be working. 🤔

**Comment by teoljungberg** [comment]
Something like this maybe?

```
augroup vimrc
  autocmd BufWritePost vimrc,$HOME/.vimrc,$MYVIMRC nested if expand("%") !~ 'fugitive' | source % | endif
augroup END
```

**Comment by gabebw** [comment]
The fix in 5e2e309fc93aa6129c711d61c595f32dc8d422a1 doesn't work, as tested by:

* Add `let g:x = 1` to `~/.vimrc`
* `:w`
* `:echo g:x` raises an error, saying `g:x` isn't set

**Comment by teoljungberg** [comment]
After looking at your dotfiles it looks like your `augroup`s are overriding eachother, which is causing the auto sourcing to not work.

You have two `augroup`s named `vimrc`, where the first one has a `autocmd!` in it - which clears the `augroup` when sourcing a file. So the latter `augroup` with the autosourcing functionallity is overriden. If you rename the `augroup` that sources the file into something else like `autosource_vimrc` or merging them together - it will work as expected.

**Comment by gabebw** [comment]
Wow, great work @teoljungberg!

I did some research on why I would even use `augroup`s. Based on [the answers here](https://vi.stackexchange.com/questions/9455/why-should-i-use-augroup), it looks like:

* Yes, I should use `augroup`
* But for my `vimrc`, I probably only want one `augroup`
