### ISSUE TITLE
Italic fonts

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#111]
Yeah, iTerm2 is required, and I'm unlikely to switch from Terminal.app, but here it is: https://github.com/teoljungberg/dotfiles/pull/2

Also: https://github.com/teoljungberg/dotfiles/commit/abe18b9c274ad000eb7e62fa318ac1623ee8bd01

**Comment by teoljungberg** [comment]
In my original PR you linked iTerm2 was a prerequisite. But in the latter commit, also linked, I got italics working within Terminal.app

**Comment by gabebw** [comment]
Also check out https://fonts.google.com/specimen/IBM+Plex+Mono
