### ISSUE TITLE
Switch to rcm?

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#12]
https://thoughtbot.github.io/rcm/

https://github.com/thoughtbot/rcm

**Comment by gfontenot** [comment]
Happy to help in the transition if you want. Friday?

**Comment by gabebw** [comment]
Oh hey, sure. At the very least we can have a good discussion about the pros and cons.

**Comment by gfontenot** [comment]
:+1:

**Comment by gabebw** [comment]
Well this is very much done: #21, #22, #23, #24, #25.
