### ISSUE TITLE
Pass all Vim <TAB> completions through FZF, somehow

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#127]
Pie-in-the-sky idea: you know how Vim pops up options when autocompleting a command?

![image](https://user-images.githubusercontent.com/257678/39904706-2b2edf4a-548e-11e8-89e9-b1820eebf8b9.png)

It'd be amazing if that automatically, seamlessly went through FZF instead of having to `<TAB>` through all the options.

I know that there's `:FZF` to fuzzy find files, but I want to (in this case) pre-filter using rails.vim then call FZF on the result.

**Comment by gabebw** [comment]
Maybe use `gprof` or similar to get a call stack for this minimal Vim:

```
vim -u NONE -c 'set nocompatible'
```

Then see what gets called when you run `:he<TAB>` and hook into it?

**Comment by mavam** [comment]
Not possible or already solved? 🙂

(I want this, too.)

**Comment by gabebw** [comment]
Haha, option (C): doesn't seems as important to me now. I'd try it out if it exists, though!
