### ISSUE TITLE
Try `Ctrl-b` as tmux prefix

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#131]
My current tmux prefix is <kbd>Ctrl-a</kbd>. I'd like to use that key combo for its default use: going to the beginning of a line anywhere in the system (even in Vim command mode!). I use <kbd>Ctrl-e</kbd> to go to the end of the line all the time, so I'd use <kbd>Ctrl-a</kbd> a lot I bet.

**Comment by gfontenot** [comment]
Do you have a second to talk about Our Lord And Savior <kbd>Ctrl-s</kbd>?

**Comment by gabebw** [comment]
@gfontenot 

1) Thank you for using `<kbd>` ❤️
2) That's a good idea! Does <kbd>Ctrl-s</kbd> interfere with any standard keybindings?

**Comment by gfontenot** [comment]
Not sure! I think I learned it from @christoomey, who would certainly know the answer to that.

**Comment by odnoletkov** [comment]
<kbd>Ctrl-s</kbd> is the opposite of <kbd>Ctrl-r</kbd> in bash/readline history search mode – it selects previous (more recent) match for current query. But it doesn't usually work out of the box because it is also used for terminal flow control – you can fix this with `stty -ixon`.

**Comment by teoljungberg** [comment]
Which also means you can still use `ctrl+a` in vim/zsh/bash/whatever.

**Comment by gabebw** [comment]
I just learned that <kbd>Ctrl-b</kbd> moves to the beginning of the command line in Vim: https://stackoverflow.com/questions/10201430/how-to-quickly-scroll-to-the-latest-end-of-command-history-in-bash

I have Vim keybindings set (https://github.com/gabebw/dotfiles/blob/f95aba467fb616a5b0cb9481eb85c9589dfeba34/zshrc#L441) at the command line, so I just use standard Vim keys to move around.

I am closing this because that's really all I need.

**Comment by christoomey** [comment]
Always fun getting notifications on things like this years later 👋 Hi @gabebw, hope all is super great with you. Also, in the nature of the world being tiny, just today I was looking at your fx gem, @teoljungberg. Hoping to be able to use it on a project soon!

You're cool too, @gfontenot.

**Comment by teoljungberg** [comment]
That's lovely to hear @christoomey!

**Comment by gabebw** [comment]
Hi Chris, just got a job at [Grammarly](https://www.grammarly.com) starting May 19th! I'm excited to start doing more Typescript (and thus #163 is becoming more urgent 😄). I saw you started freelancing recently - I know you'll do well ❤️!
