### ISSUE TITLE
Check out fish shell

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#140]
https://github.com/thorncp/dotfiles/commit/39daa5d6e2d8bec825aa7ccb38e454862f4ee2aa#commitcomment-29773674

Stuff it does out of the box:

* Good/bad commands are green/red (like zsh-syntax-highlighting)
* Amazing, colorful git autocomplete
* Autocomplete loads without any extra config (like having to call `autoload -Uz compinit`), and loads quickly

WIP: https://github.com/gabebw/dotfiles/compare/gbw-fish-shell

## To do

- [x] Use `-` as abbreviation for `cd -`
  - Yes, [per the docs](https://fishshell.com/docs/current/faq.html#faq-cd-minus): `abbr -a -- - 'cd -'`
- [x] How to complete one command like another (e.g. `staging` like `heroku`)?
  - `complete -c production -w heroku`
- [x] Complete `gc` like `git checkout`? (This is different because `git checkout` is a subcommand.)
  - Looks like this is [available in Fish 3.0b1](https://github.com/fish-shell/fish-shell/issues/1976#issuecomment-369046742): `complete gc -w 'git checkout'`
- [x] Enable vim editing mode on command line
  - `fish_vi_key_bindings`, which automatically shows which mode you're in!
- [x] How to complete `viw` like `which` (i.e. with everything in $PATH or any alias)
- [x] Does fish automatically recognize and complete commands that have been installed since the last time the fish config was sourced?

## Configs

* Josh: https://github.com/jcmorrow/dotfiles/pull/13

**Comment by gabebw** [comment]
It can run standard shell syntax by prefixing a command with `bash`.

**Comment by gabebw** [comment]
Some fish configs: https://github.com/search?utf8=%E2%9C%93&q=extension%3Afish+set&type=Code&chrome_dont_add_custom_search_engines_srsly=

**Comment by gabebw** [comment]
Looks like Homebrew installs its fish completions in `/usr/local/share/fish/vendor_completions.d`.

**Comment by gabebw** [comment]
It looks like Fish doesn't have an equivalent to Zsh's better-than-`test` syntax of `[[ ... ]]`, instead relying on `set -q` (for `test -n`) or `test`. 

That's unfortunate because I want `[[ $x = $y ]]`  to "just work", without me having to worry about `=` vs `-eq`.

**Comment by jsatk** [comment]
@gabebw I'm a huge fish shell fan. Been using since 2013. Let me know if you want any help/advice 😄 My dotfiles have a lot of fish stuff too.
