### ISSUE TITLE
colorls

### ISSUE THREAD

**Issue by adarsh** [gabebw/dotfiles#145]
Check this out: https://github.com/athityakumar/colorls

> A Ruby script that colorizes the ls output with color and icons. Here are the screenshots of working example on an iTerm2 terminal (Mac OS), oh-my-zsh with powerlevel9k theme and powerline nerd-font + awesome-config font with the Solarized Dark color theme.

![colorls](https://user-images.githubusercontent.com/17109060/32149040-04f3125c-bd25-11e7-8003-66fd29bc18d4.png)

**Comment by gabebw** [comment]
Nice! I'm used to my existing `ls` colors, though, and I'm cleaning up old issues, so: closing. ❤️
