### ISSUE TITLE
Auto-pbcopy pull request URL with `hub pull-request`

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#17]
`hub pull-request` pops open Vim, prints out some debugging git output, then prints the GitHub PR URL. I want to copy that URL.

`hub pull-request | pbcopy` doesn't work, because Vim really doesn't like being piped to another process.

One idea:

```bash
$ vim /tmp/commitmsg && hub pull-request -m $(cat /tmp/commitmsg) | pbcopy
$ rm /tmp/commitmsg
```

Wrinkle:

`hub pull-request` shows a helpful commit message template that includes commit messages since master. I'd like to keep that. It uses [this code](https://github.com/github/hub/blob/0900df0104e2422180b6377e471b2a320730f13c/commands/pull_request.go#L238-L261) to do that.

According to [the `git.Log()` code](https://github.com/github/hub/blob/0900df0104e2422180b6377e471b2a320730f13c/git/git.go#L141-L155), this should replicate that template:

```
git log --format="%h (%aN, %ar)%n%w(78,3,3)%s%n%+b" | sed 's/^/# /'
```

**Comment by r00k** [comment]
Can't wait for you to solve this. I really want it too.

**Comment by r00k** [comment]
I wonder if @pbrisbin would have ideas...

**Comment by pbrisbin** [comment]
This is tricky and I have no immediately solutions. I could offer a (disappointing) workaround though: most terminals have a way to map a key to find URLs and copy or open them. This is what I do for this workflow. `hub` naturally prints the PR in the terminal and then a quick `Alt-u` to open it (which could easily be made to copy instead).

**Comment by gfontenot** [comment]
took a stab at this: gfontenot/dotfiles#19

**Comment by gabebw** [comment]
Check out #17.
