### ISSUE TITLE
.curlrc breaks vagrant

### ISSUE THREAD

**Issue by sndpl** [gabebw/dotfiles#29]
Hi, nice dotfiles but maybe you can add a comment line in the ```.curlrc``` file that the user-agent line will break vagrant (https://www.vagrantup.com/), took me some time to discover this file (that looked very handy) was the problem.

Vagrant downloads boxes metadata with curl and uses a custom user-agent, else it doesn't return json but text/html and then you get some strange error's :( Will also create an issue for vagrant so they can handle the error a bit better.

**Comment by gabebw** [comment]
I just ran into this issue too. I fixed it by removing all headers from my .curlrc: 3880331fb4081e957a1f9923f109d299efeeebfe
