### ISSUE TITLE
gitsh

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#31]
https://github.com/gfontenot/dotfiles/blob/3c438f60566e00e55f1cb2d3f5fe259978e04923/tag-git/config/git/config#L93-L97

**Comment by adarsh** [comment]
Same here: Are you really feeling this pain?

**Comment by gabebw** [comment]
I'm worried it's like rcm where I wasn't feeling the pain and then I try it out and am like "OHOHOHOHO this is _excellent_ where have u been all my life rcm/gitsh"

**Comment by gabebw** [comment]
"worried" is obviously a strong word here.

**Comment by adarsh** [comment]
Then try it tomorrow!

On Thursday, May 19, 2016, Gabe Berke-Williams <notifications@github.com>
wrote:

> "worried" is obviously a strong word here.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/gabebw/dotfiles/issues/31#issuecomment-220507764>
>


-- 


-- 
@adarshp <http://www.twitter.com/adarshp>
313.454.1515 (mobile)
See when I am free: http://bit.ly/adarshcal

**Comment by gfontenot** [comment]
FWIW, [this](https://github.com/gfontenot/dotfiles/blob/master/tag-tmux/config/tmux/keybindings.tmux#L6-L7) is when gitsh really clicked for me.
