### ISSUE TITLE
Enable Syntastic for shell files

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#34]
Syntastic automatically looks for `shellcheck` if it's installed, so enable Syntastic for shell files.

**Comment by gabebw** [comment]
https://github.com/gabebw/dotfiles/tree/gbw-syntastic

**Comment by gabebw** [comment]
I have syntastic mostly turned off: https://github.com/gabebw/dotfiles/blob/master/tag-haskell/vim/rcplugins/syntastic.vim

How do I turn it on for just shell scripts and Haskell?

**Comment by gfontenot** [comment]
`ftplugin`?

**Comment by gabebw** [comment]
Can you expand on that? Do you have a Syntastic configuration I could look at?

**Comment by gfontenot** [comment]
I don't, and I'm not sure that I know what I'm talking about. Is there a reason to not add the various shell filetypes next to `haskell` in your `passive_filetypes` key though?

**Comment by gabebw** [comment]
I figured out how to enable it for everything, but I find that it's not as useful as I thought it would be. I'm closing.
