### ISSUE TITLE
Replace Ctrl-p with FZF?

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#42]
https://github.com/gfontenot/dotfiles/commit/3868300cf354ccb16990e3904600e9484a286765

**Comment by gfontenot** [comment]
It's got some rough-ish edges but all in all I'm enjoying it.

**Comment by gfontenot** [comment]
[the commands it exposes, for example, are pretty amazing](https://github.com/junegunn/fzf.vim#commands). No way I'll use all of them but it's awesome to have them available.

**Comment by jayroh** [comment]
👋 hi guys

I've been meaning to make this same change. Even more so now to see how it performs if I throw `ripgrep` instead of `ag`.

Listened to Derek and Sean talk about it on the bikeshed so figure, wtf why not?

**Comment by gabebw** [comment]
Done in b0b9007368a2a6803ce65cba94e23edee38b5b3a.

The little window that pops up for FZF looks way nicer than the Ctrl-P one, too.
