### ISSUE TITLE
Look into this

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#44]
It has the words "fzf" and "tmux" so it's probably good https://github.com/gfontenot/dotfiles/commit/ea40b2a4f28b344bb16d16434a5638fad8981209

**Comment by gfontenot** [comment]
it's _very_ good.

**Comment by gfontenot** [comment]
it also has the words @christoomey so that's 3 for 3

**Comment by gabebw** [comment]
And it's from @gfontenot so 4 for 3

**Comment by christoomey** [comment]
I'm a big fan.

Also, if you're into using tmux to jump around between sessions, I'd recommend taking a quick look at my setup for opening new sessions from a fuzzy "projects" list (git repos I've worked on recently within my `~/code` directory):

- [tmux mapping](https://github.com/christoomey/dotfiles/blob/master/tmux/tmux.conf)
- [shell function](https://github.com/christoomey/dotfiles/blob/master/tmux/tmux.conf)
- [cdpath configuration](https://github.com/christoomey/dotfiles/blob/master/zsh/config/ruby.zsh)

Almost certainly could be done more cleanly, but the functionality is real neato.

**Comment by gabebw** [comment]
@christoomey I already use the `projects` thing! It's extremely neato!

You may want to look into using a different variable than `cdpath` (like [I do here](https://github.com/gabebw/dotfiles/commit/03d8e205bf0635d411da813a23695662574f6687)).

The problem I ran into with `export $CDPATH` is that exporting makes it available to _every_ script you run in the shell. So if you run an install script that calls `cd foo` expecting to be taken to `./foo` would actually be taken to `~/Projects/code/foo`, breaking the script.

**Comment by jsteiner** [comment]
This is amazing. Ya'll are the best!

**Comment by gabebw** [comment]
I've been using FZF for a while. It's great!
