### ISSUE TITLE
Add a different git cleanup so I can start commit message lines with `#`

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#50]
Some info: https://stackoverflow.com/questions/2788092/start-a-git-commit-message-with-a-hashmark

Here's what I think has to happen:

- [ ] Figure out what the various git cleanup methods do
- [ ] Use (or create) a cleanup method that removes lines starting with something other than `#`
- [ ] Change Vim syntax highlighting for `gitcommit` files so it reads whatever the new comment character is as comments

**Comment by thorncp** [comment]
Possibly helpful? https://sdqali.in/blog/2013/04/14/configure-gits-comment-character/

**Comment by gabebw** [comment]
Maybe run `git config --set core.commentchar $` in a specific repo? That might fix everything.

**Comment by gabebw** [comment]
`git-create-pull-request` understands `core.commentchar` now: #53

**Comment by gabebw** [comment]
I'm gonna say #53 (and @thorncp's expert knowledge!) fixed this.
