### ISSUE TITLE
Please help: why is `gc` autocompletion failing?

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#69]
```
$ gc <TAB>
zsh:12: command not found: __git-checkout_main
```

I have the following lines in [my zshrc](https://github.com/gabebw/dotfiles/blob/2059f6e5a35e7b12e84c88822756bef19d78a20d/zshrc#L543-L547), and they've been working for a while:

```sh
# Complete `g` like `git`, etc
alias __git-checkout_main=_git_checkout
compdef g=git
compdef _git gc=git-checkout
compdef _git ga=git-add
```

`g checkout` does not error, so `compdef g=_git` seems to be working, and `ga` seems to autocomplete correctly. Removing the `alias` line doesn't help.

------------------------------------------

### Versions

Zsh: zsh 5.4.1 (x86_64-apple-darwin16.7.0)
Git: 2.14.1

**Comment by gfontenot** [comment]
Not sure if this is the issue but a while back I had issues with the completions that ship with `git` clobbering the ones that ship with `zsh`. I use a similar setup as yours and if I remember correctly, the completions that ship with `git` are in a format that doesn't work well with `compdef`. The completions from `zsh` are better IMO, so I just started installing `git` using `--without-completion` and all my woes were solved.

**Comment by gabebw** [comment]
`brew uninstall zsh && brew install zsh` makes the problem appear on a machine that was working fine before, so I suspect you're right.

**Comment by gabebw** [comment]
`brew install git --without-completions` fixed it! ❤️ 💖 ❤️ 💖 ❤️ 💖 

Also: Zsh completion is _wild_! It shows the latest commit message for all branches and commits all the way back to HEAD~19.

Zsh's completion doesn't work with `git bd`, though maybe I'll just turn that into an FZF command...

P.S. I forgot that I turned `gc` (`gco` for you) into [an FZF-enabled command](https://github.com/gabebw/dotfiles/blob/5c6c109b6d178d9d93dfafea6f2a91ac714d22c0/zshrc#L519-L528). This is so helpful to current me.

**Comment by gabebw** [comment]
`git bd` now fuzzy-finds, which is better anyway: 613ef8b8d2d78d2ea205843b2cb301689bb6785b

Thank you @gfontenot!
