### ISSUE TITLE
Make a `GcopyPermalinkToCurrentLineOnGithub` command

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#75]
e.g. `https://github.com/gabebw/dotfiles/blob/e5eb9d3d66829ab2417e68382963153dc77eaa61/Brewfile#L10` in the system clipboard

This would need:

* Current commit (from fugitive)
* Current line (from Vim)
* Current file (from Vim)
* Copy to system clipboard (from [vim-system-copy](https://github.com/christoomey/vim-system-copy))

**Comment by gabebw** [comment]
"maybe make the command shorter" - @gfontenot

**Comment by reshleman** [comment]
Fugitive has [`Gbrowse!`](https://github.com/tpope/vim-fugitive/blob/be2ff98db543990d7e59a90189733d7a779788fd/doc/fugitive.txt#L262-L263), which may do what you want.

It's also shorter. 😄

**Comment by gabebw** [comment]
@reshleman Wow! `:.Gbrowse! -` does _exactly_ what I want. Thank you!
