### ISSUE TITLE
Switch to asdf version manager?

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#77]
I only manage Ruby versions right now, and `rbenv` is great for that. But if I need lots of different versions of Elixir, Haskell, etc in the future, I may want to try [asdf](https://github.com/asdf-vm/asdf).

**Comment by gfontenot** [comment]
FWIW, I don't use `asdf` for Haskell, although I don't have a great reason for not using it.

**Comment by gabebw** [comment]
I use `nvm` too, now. When/If I have 3 version managers, I'll check this out.
