### ISSUE TITLE
Add a Vim snippets plugin

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#8]
Vimcasts has some content on Ultisnips, but `UltiSnipsEdit` only detect filetype sometimes, I think.

How about snipmate?

**Comment by tsigo** [comment]
I went with UltiSnips - https://github.com/tsigo/dotfiles-local/tree/master/vim/UltiSnips

I think you're right about it not always detecting the right filetype, but you can do `UltiSnipsEdit ruby`, for example.

**Comment by adarsh** [comment]
Clearly, you are not feeling this pain very much, since this issue is almost 2yo :)

**Comment by gabebw** [comment]
You are so right.
