### ISSUE TITLE
Try out kiTTY?

### ISSUE THREAD

**Issue by gabebw** [gabebw/dotfiles#96]
[Kitty](https://github.com/kovidgoyal/kitty) is "A cross-platform, fast, feature full, GPU based terminal emulator".

https://github.com/thorncp/dotfiles/commit/80c739c8efb0716e60ea589e735d5d990816d260

* My branch: https://github.com/gabebw/dotfiles/compare/gbw-kitty
* Downloads (recommended instead of Homebrew): https://github.com/kovidgoyal/kitty/releases
* Example config: https://github.com/kovidgoyal/kitty/blob/master/kitty/kitty.conf
* Put `kitty.app` in your dock and run it
* Kitty Changelog: https://sw.kovidgoyal.net/kitty/changelog.html

**Comment by gabebw** [comment]
Some helpful info: https://github.com/thorncp/dotfiles/commit/80c739c8efb0716e60ea589e735d5d990816d260#commitcomment-26240358

**Comment by gabebw** [comment]
Chris's `kitty.conf`: https://github.com/thorncp/dotfiles/blob/master/config/kitty/kitty.conf

**Comment by jcmorrow** [comment]
I'm curious about this. Chris's drawbacks sound not-insignificant.

**Comment by gabebw** [comment]
Looks like issues 1 and 2 will be fixed by the end of the week, but these will persist:

>* The font scaling seems not totally worked out for high DPI screens.
  Looks fine on my external monitor, but is so small I can't read it on
  the laptop (retina) screen. [Related issue][3].
>* The cursor does not change from a block to a vertical line when Vim
  goes into insert mode. Minor, but would be nice to have.

**Comment by thorncp** [comment]
The font scaling isn't that bad, I've been using the font size shortcuts to deal with it as needed. If you move from a non-retina screen to retina screen often, it'd probably be super annoying.

The block cursor has been less of an issue than I thought it would. I don't notice anymore.

It's freaking fast! I did not know how responsive a terminal could be until trying it.

**Comment by thorncp** [comment]
The GPU issue was just resolved! https://github.com/kovidgoyal/kitty/issues/136

**Comment by jcmorrow** [comment]
OK, that’s enough for me to give it a try then!

**Comment by gabebw** [comment]
I installed it via the Mac DMG package and it appears to not be reading the config in `~/.config/kitty/kitty.conf` at all :(

**Comment by gabebw** [comment]
Kitty also processes trailing spaces oddly:

* When my `$PROMPT` ends in 1 space, the space is removed
* When my `$PROMPT` ends in 2 spaces, both spaces are shown

I can't win 😞

**Comment by gabebw** [comment]
>Kitty also processes trailing spaces oddly:

That issue is fixed now.

**Comment by gabebw** [comment]
New problem: in Vim, when I press `<Ctrl>--` to comment a line triggers the command bound to `-`, as if I hadn't pressed `<Ctrl>` at all.

**Comment by gabebw** [comment]
It really is fast, though.

**Comment by gabebw** [comment]
BONUS: it handles emoji in the prompt just fine, thus fixing #109.

**Comment by gabebw** [comment]
And the `xterm-kitty` terminfo that Kitty uses supports italics out of the box!

**Comment by gabebw** [comment]
Kitty is _almost_ there (and has hot pink URLs: b43842d) but still does some weird stuff:

* There's a real weird issue with the <kbd>Ctrl+minus</kbd> mapping in Vim. Kitty only triggers it on <kbd>Ctrl+shift+minus</kbd>
* Ligatures (as in Iosevka) are [not supported](https://github.com/kovidgoyal/kitty/issues/50):

<img width="121" alt="kitty 2018-04-29 10-49-00" src="https://user-images.githubusercontent.com/257678/39409385-ef2b5934-4b9a-11e8-9132-33d1a9c00e38.png">

Compare to Terminal:

<img width="106" alt="terminal 2018-04-29 10-49-11" src="https://user-images.githubusercontent.com/257678/39409388-f746f362-4b9a-11e8-8c8e-249c6fa41bdc.png">

**Comment by gabebw** [comment]
Iosevka ligature update, seems like this is exactly my issue: https://github.com/kovidgoyal/kitty/issues/297

**Comment by gabebw** [comment]
Re: ligatures again, there's always Iosevka Term and Iosevka Term Italic, which don't have ligatures. No ligatures is better than weird ligatures.

**Comment by gabebw** [comment]
Text hint mode is wild! dcfa27f05134d51e94f502147315b67385143d21

**Comment by gabebw** [comment]
It's annoying that Kitty can't connect to tmux sessions opened by Terminal.app:

```
open terminal failed: can't find terminfo database
```

Known (tmux) issue, but annoying: https://github.com/kovidgoyal/kitty/issues/370

(To be fair, if I switch to always using Kitty, then this wouldn't be a problem.)

**Comment by gabebw** [comment]
Kitty can run diffs in the terminal now?!

https://sw.kovidgoyal.net/kitty/kittens/diff.html

(It even works on images.)

**Comment by srounce** [comment]
> There's a real weird issue with the Ctrl+minus mapping in Vim. Kitty only triggers it on Ctrl+shift+minus

RT(F)M: https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.kitty_mod

**Comment by jcmorrow** [comment]
Oh wow, thanks @srounce, adding `kitty_mod super` to my config!

**Comment by srounce** [comment]
Sorry didn't mean to be so abrasive with the RTFM bit. Reading it back seems a bit overly aggressive.
